apiVersion: v1
kind: ClusterRoleBinding
metadata:
  labels:
    template: cronjob-prune-images
  name: {{ .Values.namespace }}-image-pruners
roleRef:
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ .Values.job_service_account }}
userNames:
- system:serviceaccount:{{ .Values.namespace }}:{{ .Values.job_service_account }}
