apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    template: cronjob-prune-builds-deployments
  name: {{ .Values.namespace }}-{{ .Values.prune_type }}-pruners
roleRef:
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ .Values.job_service_account }}
userNames:
- system:serviceaccount:{{ .Values.namespace }}:{{ .Values.job_service_account }}
